### PR TITLE
fix several minor issues

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
list of fixes:

- handle unicode encoded messages
- dump messages in separate lines to file
- respect requested fields when dumping
- read password from config file

unfortunately I discovered the tests too late, so while they still pass, I didn't add any new tests to cover the things i fixed... that totally and immediately goes on the todo list though : )

### CODE REVIEW

**Comment by josegonzalez** [comment]
Tests actually appear to fail with a newline error. Mind fixing that up?

**Comment by valentin-krasontovitsch** [comment]
Of course, I'll take a look at it!
Would you mind posting a bit more info so I can reproduce more quickly and
know what you're referring to?

**Comment by josegonzalez** [comment]
The tests are linked via travis-ci, and here is a failing run: https://travis-ci.org/blue-yonder/bonfire/jobs/376320016

**Comment by valentin-krasontovitsch** [comment]
duh, of course they are... thanks : )
gonna fix asap.

**Comment by valentin-krasontovitsch** [comment]
closing in favor of #34

**Pull request closed without merging**
